using System.Collections.Generic;
using System.Windows.Forms;
using MonoGameKeys = Microsoft.Xna.Framework.Input.Keys;

namespace MonoGame.Forms.Utils
{
    internal static class KeyboardUtil
    {
        private static Dictionary<Keys, MonoGameKeys> KeyboardMapping;

        static KeyboardUtil()
        {
            KeyboardMapping = new Dictionary<Keys, MonoGameKeys>() {
                { Keys.A, MonoGameKeys.A },
                { Keys.Add, MonoGameKeys.Add },
                { Keys.Alt, MonoGameKeys.LeftAlt },
                { Keys.Apps, MonoGameKeys.Apps },
                { Keys.Attn, MonoGameKeys.Attn },
                { Keys.B, MonoGameKeys.B },
                { Keys.Back, MonoGameKeys.Back },
                { Keys.BrowserBack, MonoGameKeys.BrowserBack },
                { Keys.BrowserFavorites, MonoGameKeys.BrowserFavorites },
                { Keys.BrowserForward, MonoGameKeys.BrowserForward },
                { Keys.BrowserHome, MonoGameKeys.BrowserHome },
                { Keys.BrowserRefresh, MonoGameKeys.BrowserRefresh },
                { Keys.BrowserSearch, MonoGameKeys.BrowserSearch },
                { Keys.BrowserStop, MonoGameKeys.BrowserStop },
                { Keys.C, MonoGameKeys.C },
                { Keys.CapsLock, MonoGameKeys.CapsLock },
                { Keys.Crsel, MonoGameKeys.Crsel },
                { Keys.D, MonoGameKeys.D },
                { Keys.D0, MonoGameKeys.D0 },
                { Keys.D1, MonoGameKeys.D1 },
                { Keys.D2, MonoGameKeys.D2 },
                { Keys.D3, MonoGameKeys.D3 },
                { Keys.D4, MonoGameKeys.D4 },
                { Keys.D5, MonoGameKeys.D5 },
                { Keys.D6, MonoGameKeys.D6 },
                { Keys.D7, MonoGameKeys.D7 },
                { Keys.D8, MonoGameKeys.D8 },
                { Keys.D9, MonoGameKeys.D9 },
                { Keys.Decimal, MonoGameKeys.Decimal },
                { Keys.Delete, MonoGameKeys.Delete },
                { Keys.Divide, MonoGameKeys.Divide },
                { Keys.Down, MonoGameKeys.Down },
                { Keys.E, MonoGameKeys.E },
                { Keys.End, MonoGameKeys.End },
                { Keys.Enter, MonoGameKeys.Enter },
                { Keys.EraseEof, MonoGameKeys.EraseEof },
                { Keys.Escape, MonoGameKeys.Escape },
                { Keys.Execute, MonoGameKeys.Execute },
                { Keys.Exsel, MonoGameKeys.Exsel },
                { Keys.F, MonoGameKeys.F },
                { Keys.F1, MonoGameKeys.F1 },
                { Keys.F10, MonoGameKeys.F10 },
                { Keys.F11, MonoGameKeys.F11 },
                { Keys.F12, MonoGameKeys.F12 },
                { Keys.F13, MonoGameKeys.F13 },
                { Keys.F14, MonoGameKeys.F14 },
                { Keys.F15, MonoGameKeys.F15 },
                { Keys.F16, MonoGameKeys.F16 },
                { Keys.F17, MonoGameKeys.F17 },
                { Keys.F18, MonoGameKeys.F18 },
                { Keys.F19, MonoGameKeys.F19 },
                { Keys.F2, MonoGameKeys.F2 },
                { Keys.F20, MonoGameKeys.F20 },
                { Keys.F21, MonoGameKeys.F21 },
                { Keys.F22, MonoGameKeys.F22 },
                { Keys.F23, MonoGameKeys.F23 },
                { Keys.F24, MonoGameKeys.F24 },
                { Keys.F3, MonoGameKeys.F3 },
                { Keys.F4, MonoGameKeys.F4 },
                { Keys.F5, MonoGameKeys.F5 },
                { Keys.F6, MonoGameKeys.F6 },
                { Keys.F7, MonoGameKeys.F7 },
                { Keys.F8, MonoGameKeys.F8 },
                { Keys.F9, MonoGameKeys.F9 },
                { Keys.G, MonoGameKeys.G },
                { Keys.H, MonoGameKeys.H },
                { Keys.Help, MonoGameKeys.Help },
                { Keys.Home, MonoGameKeys.Home },
                { Keys.I, MonoGameKeys.I },
                { Keys.IMEConvert, MonoGameKeys.ImeConvert },
                { Keys.IMENonconvert, MonoGameKeys.ImeNoConvert },
                { Keys.Insert, MonoGameKeys.Insert },
                { Keys.J, MonoGameKeys.J },
                { Keys.K, MonoGameKeys.K },
                { Keys.KanaMode, MonoGameKeys.Kana },
                { Keys.KanjiMode, MonoGameKeys.Kanji },
                { Keys.NumPad0, MonoGameKeys.NumPad0 },
                { Keys.NumPad1, MonoGameKeys.NumPad1 },
                { Keys.NumPad2, MonoGameKeys.NumPad2 },
                { Keys.NumPad3, MonoGameKeys.NumPad3 },
                { Keys.NumPad4, MonoGameKeys.NumPad4 },
                { Keys.NumPad5, MonoGameKeys.NumPad5 },
                { Keys.NumPad6, MonoGameKeys.NumPad6 },
                { Keys.NumPad7, MonoGameKeys.NumPad7 },
                { Keys.NumPad8, MonoGameKeys.NumPad8 },
                { Keys.NumPad9, MonoGameKeys.NumPad9 },
                { Keys.Multiply, MonoGameKeys.Multiply },
                { Keys.L, MonoGameKeys.L },
                { Keys.LaunchApplication1, MonoGameKeys.LaunchApplication1 },
                { Keys.LaunchApplication2, MonoGameKeys.LaunchApplication2 },
                { Keys.LaunchMail, MonoGameKeys.LaunchMail },
                { Keys.LControlKey, MonoGameKeys.LeftControl },
                { Keys.Left, MonoGameKeys.Left },
                { Keys.LShiftKey, MonoGameKeys.LeftShift },
                { Keys.LWin, MonoGameKeys.LeftWindows },
                { Keys.M, MonoGameKeys.M },
                { Keys.MediaNextTrack, MonoGameKeys.MediaNextTrack },
                { Keys.MediaPlayPause, MonoGameKeys.MediaPlayPause },
                { Keys.MediaPreviousTrack, MonoGameKeys.MediaPreviousTrack },
                { Keys.MediaStop, MonoGameKeys.MediaStop },
                { Keys.N, MonoGameKeys.N },
                { Keys.None, MonoGameKeys.None },
                { Keys.NumLock, MonoGameKeys.NumLock },
                { Keys.O, MonoGameKeys.O },
                { Keys.Oem8, MonoGameKeys.Oem8 },
                { Keys.OemBackslash, MonoGameKeys.OemPipe },   // MonoGame Issue 1012
                { Keys.OemClear, MonoGameKeys.OemClear },
                { Keys.OemCloseBrackets, MonoGameKeys.OemCloseBrackets },
                { Keys.Oemcomma, MonoGameKeys.OemComma },
                { Keys.OemMinus, MonoGameKeys.OemMinus },
                { Keys.OemOpenBrackets, MonoGameKeys.OemOpenBrackets },
                { Keys.OemPeriod, MonoGameKeys.OemPeriod },
                { Keys.Oemplus, MonoGameKeys.OemPlus },
                { Keys.OemQuestion, MonoGameKeys.OemQuestion },
                { Keys.OemQuotes, MonoGameKeys.OemQuotes },
                { Keys.OemSemicolon, MonoGameKeys.OemSemicolon },
                { Keys.Oemtilde, MonoGameKeys.OemTilde },
                { Keys.P, MonoGameKeys.P },
                { Keys.Pa1, MonoGameKeys.Pa1 },
                { Keys.PageDown, MonoGameKeys.PageDown },
                { Keys.PageUp, MonoGameKeys.PageUp },
                { Keys.Pause, MonoGameKeys.Pause },
                { Keys.Play, MonoGameKeys.Play },
                { Keys.Print, MonoGameKeys.Print },
                { Keys.PrintScreen, MonoGameKeys.PrintScreen },
                { Keys.ProcessKey, MonoGameKeys.ProcessKey },
                { Keys.Q, MonoGameKeys.Q },
                { Keys.R, MonoGameKeys.R },
                { Keys.RControlKey, MonoGameKeys.RightControl },
                { Keys.Right, MonoGameKeys.Right },
                { Keys.RShiftKey, MonoGameKeys.RightShift },
                { Keys.RWin, MonoGameKeys.RightWindows },
                { Keys.S, MonoGameKeys.S },
                { Keys.Scroll, MonoGameKeys.Scroll },
                { Keys.SelectMedia, MonoGameKeys.SelectMedia },
                { Keys.Separator, MonoGameKeys.Separator },
                { Keys.Sleep, MonoGameKeys.Sleep },
                { Keys.Space, MonoGameKeys.Space },
                { Keys.T, MonoGameKeys.T },
                { Keys.Tab, MonoGameKeys.Tab },
                { Keys.U, MonoGameKeys.U },
                { Keys.Up, MonoGameKeys.Up },
                { Keys.V, MonoGameKeys.V },
                { Keys.VolumeDown, MonoGameKeys.VolumeDown },
                { Keys.VolumeMute, MonoGameKeys.VolumeMute },
                { Keys.VolumeUp, MonoGameKeys.VolumeUp },
                { Keys.W, MonoGameKeys.W },
                { Keys.X, MonoGameKeys.X },
                { Keys.Y, MonoGameKeys.Y },
                { Keys.Z, MonoGameKeys.Z },
                { Keys.Zoom, MonoGameKeys.Zoom },
            };
        }

        internal static MonoGameKeys FormsKeyToMonoGameKey(Keys key)
        {
            MonoGameKeys monoGameKey;
            if (KeyboardMapping.TryGetValue(key, out monoGameKey))
                return monoGameKey;
            else return MonoGameKeys.None;
        }
    }
}
